// react-version/src/components/CandidateComposition.jsx
import React, { Component } from "react";
import SkillAvatar from "./SkillAvatar";

export default class CandidateComposition extends Component {
  render() {
    return (
      <div className="row py-5 px-1 px-md-5 border-bottom">
        <div className="col-12">
          <div className="container text-center text-white text-uppercase">
            {this.props.candidate ? (
              <div>
                <SkillAvatar image={this.props.candidate.image} />
                <h1 className="font-weight-bold mt-5">
                  {this.props.candidate.name}
                </h1>
                <p>{this.props.candidate.profession}</p>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    );
  }
}

// vue-version/src/components/CandidateComposition.vue
<template>
  <b-row class="m-0 py-5 px-1 px-md-5">
    <b-col cols="12">
      <b-container class="text-center text-uppercase text-white">
        <app-skill-avatar :skill-image-url="candidate.image" />
        <h1 class="font-weight-bold mt-5">{{ candidate.name }}</h1>
        <p>{{ candidate.profession }}</p>
      </b-container>
    </b-col>
  </b-row>
</template>

<script>
import SkillAvatar from "@/components/SkillAvatar.vue";

export default {
  name: "CandidateComposition",
  components: {
    appSkillAvatar: SkillAvatar
  },
  props: {
    candidate: {
      type: Object,
      required: true
    }
  }
};
</script>

<style>
</style>
