// vue-version/src/components/CandidateExplanation.vue
<template>
  <b-row class="m-0 px-1 px-md-5 pt-2 pb-3">
    <b-col cols="12">
      <app-explanation-title :explanation-title="expTitle" />
      <app-explanation-texts v-for="(object, index) in array" :key="index" :object="object" />
    </b-col>
  </b-row>
</template>

<script>
import ExplanationTitle from "@/components/ExplanationTitle.vue";
import ExplanationTexts from "@/components/ExplanationTexts.vue";

export default {
  name: "CadidateExplanation",
  components: {
    appExplanationTitle: ExplanationTitle,
    appExplanationTexts: ExplanationTexts
  },
  props: {
    expTitle: {
      type: String,
      required: true,
      default: () => ""
    },
    array: {
      type: Array,
      required: true,
      default: () => []
    }
  }
};
</script>

// react-version/src/components/CandidateExplanation.jsx
import React, { Component } from "react";
import ExplanationTitle from "./ExplanationTitle";
import ExplanationTexts from "./ExplanationTexts";

export default class CandidateExplanation extends Component {
  render() {
    return (
      <div className="row px-1 px-md-5 pt-2 pb-3">
        <div className="col-12">
          {this.props.array ? (
            <div>
              <ExplanationTitle explanationTitle={this.props.expTitle} />
              <ExplanationTexts array={this.props.array} />
            </div>
          ) : null}
        </div>
      </div>
    );
  }
}
