// vue-version/src/components/CandidateContact.vue
<template>
  <b-row class="m-0 text-white text-center px-1 px-md-5 pt-2 pb-0">
    <b-col cols="12">
      <app-skill-title skill-title="Contact" />
      <p class="mb-0"><small><a class="text-white" :href="`tel:${contact.tel}`">{{contact.tel}}</a></small></p>
      <p><small><a class="text-white" :href="`tel:${contact.cel}`">{{contact.cel}}</a></small></p>
      <p><small>{{ contact.address }}</small></p>
      <p class="mb-0"><small><a class="text-white" :href="`${contact.website}`">{{contact.website}}</a></small></p>
      <p class="mb-1"><small><a class="text-white" :href="`mailto:${contact.mail}`">{{contact.mail}}</a></small></p>
    </b-col>
  </b-row>
</template>

<script>
import SkillTitle from "@/components/SkillTitle.vue";

export default {
  name: "CandidateContact",
  components: {
    appSkillTitle: SkillTitle
  },
  props: {
    contact: {
      type: Object,
      required: true,
      default: () => {}
    }
  }
};
</script>

<style lang="scss" scoped>
p {
  letter-spacing: 3px;
}
</style>

// react-version/src/components/CandidateContact.jsx
import React, { Component } from "react";
import GridLeft from "./GridLeft";
import SkillTitle from "./SkillTitle";

import "../styles/candidate-contact.css";

export default class CandidateContact extends Component {
  componentDidUpdate() {
    this.tel = `tel:${this.props.contact.tel}`;
    this.cel = `tel:${this.props.contact.cel}`;
    this.mailto = `mailto:${this.props.contact.mail}`;
  }

  tel = ``;
  cel = ``;
  mailto = ``;

  render() {
    return (
      <GridLeft>
        <SkillTitle skillTitle="Contact" />
        {this.props.contact ? (
          <div className="contact">
            <p className="mb-0">
              <small>
                <a className="text-white" href={this.tel}>
                  {this.props.contact.tel}
                </a>
              </small>
            </p>
            <p>
              <small>
                <a className="text-white" href={this.cel}>
                  {this.props.contact.cel}
                </a>
              </small>
            </p>
            <p>
              <small>{this.props.contact.address}</small>
            </p>
            <p className="mb-0">
              <small>
                <a className="text-white" href={this.props.contact.website}>
                  {this.props.contact.website}
                </a>
              </small>
            </p>
            <p className="mb-1">
              <small>
                <a className="text-white" href={this.mailto}>
                  {this.props.contact.mail}
                </a>
              </small>
            </p>
          </div>
        ) : null}
      </GridLeft>
    );
  }
}
