// vue-version/src/components/ExplanationTexts.vue
<template>
  <b-row class="m-0 pt-2 pb-0">
    <b-col cols="12">
      <h6 class="text-uppercase font-weight-bold">{{object.name}}</h6>
      <p class="mb-1"><small>{{object.date}}</small></p>
      <p class="mb-4"><small>{{object.description}}</small></p>
    </b-col>
  </b-row>
</template>

<script>
export default {
  name: "ExplanationTexts",
  props: {
    object: {
      type: Object,
      required: true,
      default: () => {}
    }
  }
};
</script>

// react-version/src/components/ExplanationTexts.jsx
import React, { Component } from "react";

export default class ExplanationTexts extends Component {
  createTexts() {
    const children = [];
    this.props.array.forEach((obj, index) => {
      children.push(
        <div className="row pt-2 pb-0" key={obj.name + index}>
          <div className="col-12">
            <h6 className="text-uppercase font-weight-bold">{obj.name}</h6>
            <p className="mb-1">
              <small>{obj.date}</small>
            </p>
            <p className="mb-4">
              <small>{obj.description}</small>
            </p>
          </div>
        </div>
      );
    });
    return children;
  }
  render() {
    return <div>{this.createTexts()}</div>;
  }
}
