// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent  {
  constructor() {
  }
}

<div class="main" *ngIf="data">
  <aside class="personal">
    <div class="content">
      <img [src]="data.thumb" />
      <h1>{{data.name}}</h1>
      <h3>{{data.profession}}</h3>

      <info-text 
        [icon]="'../assets/ico-profile.png'"
        [title]="data ? data.profile.title : ''"
        [description]="data ? data.profile.description : ''">
      </info-text>
      <info-text 
        [icon]="'../assets/ico-objective.png'"
        [title]="data ? data.objective.title : ''"
        [description]="data ? data.objective.description : ''">
      </info-text>
      <info-progress 
        [icon]="'../assets/ico-personal-skill.png'"
        [title]="data ? data.personalSkill.title : ''"
        [items]="data ? data.personalSkill.items : []">
      </info-progress>
      <info-contact
        [icon]="'../assets/ico-contact-me.png'"
        [title]="data ? data.contactMe.title : ''"
        [address]="data ? data.contactMe.address : ''"
        [email]="data ? data.contactMe.email : ''"
        [tel]="data ? data.contactMe.tel : ''"
        [webSite]="data ? data.contactMe.webSite : ''">
      </info-contact>
    </div>
  </aside>
  <aside class="professional">
    <div class="content">
      <info-xpwdate 
        [iconStyle]="'icon2'"
        [icon]="'../assets/ico-education.png'"
        [title]="data ? data.education.title : ''"
        [items]="data ? data.education.items: []">
      </info-xpwdate>
      <info-xpwdate 
        [iconStyle]="'icon2'"
        [icon]="'../assets/ico-experience.png'"
        [title]="data ? data.experience.title : ''"
        [items]="data ? data.experience.items: []">
      </info-xpwdate>
      <info-progress 
        [iconStyle]="'icon2'"
        [icon]="'../assets/ico-professional.png'"
        [title]="data ? data.professionalSkill.title : ''"
        [items]="data ? data.professionalSkill.items : []">
      </info-progress>
      <info-xpwdate 
        [iconStyle]="'icon2'"
        [icon]="'../assets/ico-award.png'"
        [title]="data ? data.award.title : ''"
        [items]="data ? data.award.items: []">
      </info-xpwdate>
    </div>
  </aside>
</div>

// src/App.vue
<template>
  <div id="app">
    <main class="content" v-for="profile in profiles" v-bind:key="profile.name">
      <section class="resume">
        <div class="user-info">
          <img src="./../files/avatar-dev.png" alt="" class="diamond-mask" />
          <h1 class="name">{{ profile.name }}</h1>
          <p class="profession">{{ profile.profession }}</p>
        </div>
        <hr class="division">
        <div class="profile-info">
          <div class="profile">
            <h2 class="subtitle">Profile</h2>
            <p>{{ profile.description }}</p>
          </div>
          <div class="contact">
            <h2 class="subtitle">Contact</h2>
            <p>
              {{ profile.contact.tel }} <br>
              {{ profile.contact.cel }}
            </p>
            <p>{{ profile.contact.address }}</p>
            <p>
              {{ profile.contact.website }}<br>
              {{ profile.contact.mail }}
            </p>
          </div>
          <div class="skills">
            <h2 class="subtitle">Skills</h2>
            <div class="skill" v-for="(skill) in profile.skills" v-bind:key="skill.name">
              <div class="skill-name">{{ skill.name }}</div>
              <progress :value="skill.value.replace('%', '')" max="100"></progress>
            </div>
          </div>
        </div>
      </section>

      <section class="work-education">
        <h2 class="title">Work experience</h2>
        <div class="experience" v-for="(experience) in profile.experience" v-bind:key="experience.name">
          <h2 class="subtitle">{{ experience.name }}</h2>
          <p>{{ experience.date }}</p>
          <p class="description">{{ experience.description }}</p>
        </div>
        <h1 class="title">Education</h1>
        <div class="education" v-for="(education) in profile.education" v-bind:key="education.date">
          <h2 class="subtitle">{{ education.name }}</h2>
          <p>{{ education.date }}</p>
          <p class="description">{{ education.description }}</p>
        </div>
      </section>
    </main>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  data () {
    return {
      profiles: []
    }
  },

  created () {
    axios.get(`//www.mocky.io/v2/5a5e38f3330000b0261923a5`)
      .then(response => {
        this.profiles = response.data
      })
  }
}
</script>
